### ISSUE TITLE
Deprecated targets

### ISSUE THREAD

**Issue by fanatid** [lgeiger/node-abi#14]
Why node v8.0.0 in deprecatedTargets?

**Comment by juliangruber** [comment]
actually, the name `deprecated` is misleading here, it means `notSupported`. Shall we rename it?

**Comment by lgeiger** [comment]
Instead of renaming (which would mean a new major version) we could instead introduce a new `futureTargets` object with node v8.0.0. I think that may be the clearest name.

@juliangruber @fanatid What do you think?

**Comment by fanatid** [comment]
+1 for `feature`! I also thought about this.
I'll do PR for this.
