### ISSUE TITLE
LTS

### ISSUE THREAD

**Issue by fanatid** [lgeiger/node-abi#17]
Why LTS field for target 4.x has condition `new Date() < new Date(2017, 4, 1)`? (same for 6.x)
what lts field means? lts at the moment? why this field not always `true`?

**Comment by lgeiger** [comment]
Node has a very clear [LTS schedule](https://github.com/nodejs/LTS), therefor we can predict when a version will be LTS.
Yes, `new Date()` gives the current date and the condition will be true until Node v4 is LTS.

**Comment by fanatid** [comment]
I know about node schedule, my question more about lts field destination.. is this field should be true when target is active lts? why not true for all lts releases?

**Comment by lgeiger** [comment]
Node v4 (like every other release) won't be supported forever and someday it'll become unmaintained. When that's the case I personally find it not appropriate anymore to call it LTS, but that may vary from use case to use case.

**Comment by fanatid** [comment]
Okay, looks like we just have different views for LTS name. I believe that if target is no supported anymore (marked as deprecated) it does not mean that target become to not LTS. Thank you that clarify you thoughts.
