### ISSUE TITLE
Why build both node and electron for `--napi`?

### ISSUE THREAD

**Issue by simonbuchan** [lgeiger/node-abi#56]
It seems strange that an addon that doesn't use any node headers other than `node-api.h` (including through `napi.h`) would have any ABI differences between Node and Electron?

The main thing I guess is that you can't guarantee that it is *only* using N-API, I myself have written a (test) N-API addon that uses `uv.h` to get at `uv_{get,open}_osfhandle()`, but then you can't guarantee it's using N-API at all.

**Comment by mafintosh** [comment]
I think that was meant for prebuildify which uses this.

(We build for both cause electron and node were indeed *not* abi compatible on windows for a while. Unsure if that has been fixed)

**Comment by simonbuchan** [comment]
I'm as confused as you! Possibly switched to the wrong tab. I'm not using `prebuildify` any more, (instead using `node-gyp` as a library directly) but I suppose it's still a reasonable question, I'm just not sure if it's for `prebuildify` or `electron`!
