### ISSUE TITLE
Could not detect abi for version 4.1.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron

### ISSUE THREAD

**Issue by gazxm** [lgeiger/node-abi#60]
Error: Could not detect abi for version 4.1.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron

package.json {
  ...
  "node-abi": "^2.7.1",
  ...
}

**Comment by MarshallOfSound** [comment]
Please ensure that `node-abi` is completely up to date, running off of the latest release I get this

![image](https://user-images.githubusercontent.com/6634592/54595379-b8ec0e00-49ef-11e9-911f-70d8fe81c222.png)

Which clearly shows Electron 4.1.0 working 👍

**Comment by gazxm** [comment]
ok, this is the problem of electron-rebuild. electron-rebuild version 1.8.2 -> 1.8.4 is well
