### ISSUE TITLE
Support for electron v6.0.0

### ISSUE THREAD

**Issue by thevirajshelke** [lgeiger/node-abi#68]
I have just updated my electron version to 6.0.0. While rebuilding SQLite3 with electron-rebuild I am getting the following error.

```txt
An unhandled error occurred inside electron-rebuild
Could not detect abi for version 6.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron

Error: Could not detect abi for version 6.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
```

I am able to rebuild the SQLite package using electron-builder. I am using `npx electron-builder install-app-deps`.

**Comment by barryajones** [comment]
I'm not sure but I think we just need to add a new target to the [supportedTargets](https://github.com/lgeiger/node-abi/blob/master/index.js#L72)

```javascript
{runtime: 'electron', target: '6.0.0', abi: '73', lts: false}
```

**Comment by thevirajshelke** [comment]
They have updated the package to v2.10.0 & have added support for electron v6.0.0. Closing this issue :)
