### ISSUE TITLE
Not support Electron 8.1.x

### ISSUE THREAD

**Issue by s524797336** [lgeiger/node-abi#81]
Please support it, electron-forge will fail at start script.

**Comment by zenjava** [comment]
me too.

**Comment by malept** [comment]
As far as I'm aware, the latest version of node-abi (2.15.0 at the time of this comment) supports Electron 8.1.x

**Comment by Jocs** [comment]
@s524797336 @zenjava You can check whether you install the correct version of `node-abi` in `yarn.lock` or other lock file. if not you can add codes bellow:

```json
  "resolutions": {
    "node-abi": "2.15.0"
  },
```

in your package.json file. make sure you use `yarn`.

**Comment by s524797336** [comment]
I switch to npm and reinstall, it woks...

**Comment by malept** [comment]
All you need to do is run `yarn upgrade node-abi` or `npm upgrade node-abi --depth=100` to upgrade node-abi for your project.
