### ISSUE TITLE
Could not detect abi for version 11.0.0 and runtime electron.

### ISSUE THREAD

**Issue by LaneSh4d0w** [lgeiger/node-abi#97]
It seems that node-abi does not support correctly the latest electron version, named 11.

Here is, for example, the full error brought up by "electron-rebuild" :

An unhandled error occurred inside electron-rebuild
Could not detect abi for version 11.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron

**Comment by adriencohen** [comment]
The following patch with patch-package (https://www.npmjs.com/package/patch-package) should do the trick while waiting for an update of node-abi

```
diff --git a/node_modules/node-abi/abi_registry.json b/node_modules/node-abi/abi_registry.json
index 852f500..632a1ae 100644
--- a/node_modules/node-abi/abi_registry.json
+++ b/node_modules/node-abi/abi_registry.json
@@ -88,5 +88,12 @@
     "lts": false,
     "future": true,
     "abi": "85"
+  },
+  {
+    "runtime": "electron",
+    "target": "11.0.0",
+    "lts": false,
+    "future": true,
+    "abi": "85"
   }
 ]
```

**Comment by julianxhokaxhiu** [comment]
What about opening a PR for this? Shall I do it?

**Comment by adriencohen** [comment]
@julianxhokaxhiu pretty sure it'll be done automatically tonight by the Github Action

**Comment by LaneSh4d0w** [comment]
Can confirm that latest release fixes this issue. Closing this issue.
